package z:credential-prover@0.1.0;

world credential-prover {
  import host:tenant/tenant-context@1.0.0;
  import host:interfaces/logging@2.1.0;
  import host:interfaces/kv-store@2.1.0;
  import host:interfaces/signing@2.1.0;

  export contracts;
}

interface contracts {
  record generic-input {
    input:        option<list<u8>>,
    user-profile: option<list<u8>>,
    context:      option<list<u8>>,
  }

  prove-credential: func(req: generic-input) -> result<list<u8>, string>;
  get-status:       func(req: generic-input) -> result<list<u8>, string>;
}
